# Generated by Django 4.2 on 2024-08-23 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 18, 37, 22, 631687, tzinfo=datetime.timezone.utc)),
        ),
    ]
